### ISSUE TITLE
Extend schema to allow for a conversion service to be specified

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.core#55]
- [x] Extend geppetto simulation schema to allow for specifying a conversion service in the simulator block.
- [x] Update geppetto simulation file [documentation](http://docs.geppetto.org/en/latest/simtutorial.html)

 
See below for an example:
```
<tns:entity>
	 <tns:id>hhcell</tns:id>
	 <tns:aspect>
	 	<tns:id>electrical</tns:id>
	 	<tns:simulator>
	 		<tns:simulatorId>jLemsSimulator</tns:simulatorId>
	<tns:conversionServiceId>NeuroMLConversionService</tns:conversionServiceId>
		 </tns:simulator>
		 <tns:model>
			<tns:modelInterpreterId>lemsModelInterpreter</tns:modelInterpreterId>
			<tns:modelURL>https://raw.github.com/openworm/org.geppetto.samples/master/LEMS/SingleComponentHH/LEMS_NML2_Ex5_DetCell.xml</tns:modelURL>
		 </tns:model>
	 </tns:aspect> 
</tns:entity>
```

**Comment by adrianq** [comment]
@tarelli At the moment when unmarshalling we are not validating the file/string with the schema (See https://github.com/openworm/org.geppetto.simulation/blob/master/src/main/java/org/geppetto/simulation/SimulationConfigReader.java).  Is there any reason not to do so?

**Comment by tarelli** [comment]
@adrianq no, we should

**Comment by adrianq** [comment]
@tarelli I have created a PR for core and simulation bundles that implement the schema validation. I have added some comments to both of them. Please, read them carefully and if you want to discuss them more in detail just drop a line

**Comment by adrianq** [comment]
To bare in mind that if we finally merge this PR the Geppetto documentation needs to be updated as well.
