### ISSUE TITLE
Figure out why reading values from recordings doesn't start from the first step

### ISSUE THREAD

**Issue by gidili** [openworm/org.geppetto.core#73]

**Comment by jrmartin** [comment]
There's a variable that keeps track of steps in ASimulator class. It starts at position 0, but first time is used is after already increasing one step. https://github.com/openworm/org.geppetto.core/blob/master/src/main/java/org/geppetto/core/simulator/ASimulator.java#L85 . I wouldbring it down to -1.

**Comment by gidili** [comment]
@jrmartin thanks, saw that. I will take a deeper look tomorrow - I'll let you know if I need help! ;)

**Comment by gidili** [comment]
[This commit](https://github.com/openworm/org.geppetto.core/commit/acc300fd3dea0b6e8b388ab374242308bdbe4187) took care of all problems with skipping steps due to nested entities, now the counter is only increased after all aspects have been processed rather than once per aspect that was causing the counter to be increased too often and recording steps to be skipped.
