### ISSUE TITLE
Stopping and restarting a recording results in NullPointer

### ISSUE THREAD

**Issue by gidili** [openworm/org.geppetto.core#74]
![screenshot 2015-05-12 20 21 52](https://cloud.githubusercontent.com/assets/68134/7596306/9f2ba4ae-f8e4-11e4-99e4-9e49df4df95e.png)

**Comment by gidili** [comment]
This one has to do with the recording counter not being reset when the simulation is stopped or when the recording reaches the end. Looking into it now.

**Comment by tarelli** [comment]
Obsolete
